#!/bin/bash

# Copyright (C) LA Sistemas - All Rights Reserved.
#
# Written by Leonardo - ledharaujo@gmail.com, May 2022.
#
# Unauthorized copying of this file, via any medium, is strictly prohibited.
# Proprietary and confidential.


# Constants.
VERSION='1.1.0'

# Functions.
function banner {
  echo "
    Welcome to the command-line interface.

    - Powered by LA Sistemas.
  "

  echo "
    #     #
    ##   ##     #     ####   #    #  ######  #       #       ######
    # # # #     #    #    #  #    #  #       #       #       #
    #  #  #     #    #       ######  #####   #       #       #####
    #     #     #    #       #    #  #       #       #       #
    #     #     #    #    #  #    #  #       #       #       #
    #     #     #     ####   #    #  ######  ######  ######  ######
  "
}

function show_help {
  echo "
    Usage: michelle [command] [options]

    Displays help information.

    Options:

      -h, --help                    Output usage information.
      -v, --version                 Output version of this CLI.

    Commands:
      acp [branch]                  It's a combination of git add ., git commit and git push -u origin [branch].
      find [file name]              It's a alias to find a file on current directory.
  "
}

function acp {
  git add . && git commit && git push -u origin $1
}

function find_file {
  if [ "$1" != '' ]; then
    file=$(find . -name $1)

    if [ "$file" == '' ]; then
      echo 'File not found.'

    else
      for f in $file
      do
        echo $f
      done
    fi
  fi
}

# Process micelle-cli.
if [ -z $1 ]; then
  banner

elif [ -n $1 ] && [ $1 == '-v' ] || [ $1 == '--version' ]; then
  echo $VERSION

elif [ -n $1 ] && [ $1 == 'acp' ] && [ "$2" != '' ]; then
  acp $2

elif [ -n $1 ] && [ $1 == '-h' ] || [ $1 == '--help' ]; then
  show_help

elif [ -n $1 ] && [ $1 == 'find' ]; then
  if [ -n $2 ]; then
    find_file $2

  else
    echo 'Invalid command. run 'michelle -h' for help.'
  fi

else
  echo 'Command not found. run 'michelle -h' for help.'
fi

