#!/bin/bash


# Copyright (C) LA Sistemas - All Rights Reserved.
#
# Written by Leonardo - ledharaujo@gmail.com, May 2022.
#
# Unauthorized copying of this file, via any medium, is strictly prohibited.
# Proprietary and confidential.


# Functions.
function banner {

  echo "
    Welcome to the command-line interface.

    - Powered by LA Sistemas.
  "

  echo "
    #     #
    ##   ##     #     ####   #    #  ######  #       #       ######
    # # # #     #    #    #  #    #  #       #       #       #
    #  #  #     #    #       ######  #####   #       #       #####
    #     #     #    #       #    #  #       #       #       #
    #     #     #    #    #  #    #  #       #       #       #
    #     #     #     ####   #    #  ######  ######  ######  ######
  "
}


# Process micelle-cli.
banner
